<a href="https://colab.research.google.com/github/RD191295/Pytorch-Tutorials/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##📗 Pytorch Fundamentals

### 📕***Introduction to Pytorch***
<p align="justify"> PyTorch is an open-source library used in machine learning library developed using Torch library for *python* program. It is developed by Facebook’s AI Research lab and released in January 2016 as a free and open-source library mainly used in computer vision, deep learning, and natural language processing applications. Programmer can build a complex neural network with ease using PyTorch as it has a core data structure, Tensor, multi-dimensional array like Numpy arrays. PyTorch use is increasing in current industries and in the research community as it is flexible, faster, easy to get the project up and running, due to which PyTorch is one of the top deep learning tools.<p>



🔖**Source Link:** https://pytorch.org/

In [45]:
import torch
print(torch.__version__)

1.12.1+cu113


In [46]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## 📗Introduction to Tensors

###📕Creating Tensors

🔖**Source Link**: https://pytorch.org/docs/stable/tensors.html

In [47]:
# Scalar 
scalar  = torch.tensor(7)
scalar

tensor(7)

In [48]:
# Scalar has no dimension !!
scalar.ndim

0

In [49]:
# Vectors
Vector = torch.tensor([7,1])
Vector

tensor([7, 1])

In [50]:
# Vector has 1 dimension!!
Vector.ndim

1

In [51]:
# Vector shape
Vector.shape

torch.Size([2])

In [52]:
# Matric
Matrix = torch.tensor([[7, 8],
                       [9, 10]])

Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [53]:
# Matric has 2 dim
Matrix.ndim

2

In [54]:
# Matrix shape
Matrix.shape

torch.Size([2, 2])

In [55]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [56]:
# Tensor dimension --- it has N dimension
TENSOR.ndim

3

In [57]:
# Tensor shape
TENSOR.shape

torch.Size([1, 3, 3])

In [58]:
# Tensor Example 2
Tensor_2 = torch.tensor([[[1,2,3],
                          [3,2,5]],
                         [[4,3,5],
                          [5,6,7]]])
Tensor_2

tensor([[[1, 2, 3],
         [3, 2, 5]],

        [[4, 3, 5],
         [5, 6, 7]]])

In [59]:
# Tensor_2 Shape
Tensor_2.shape

torch.Size([2, 2, 3])

### 📕 Random Tensors

Why Random Tensors❓

Random tensors are important because the way many nerual networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``` 
Start with random numbers --> look at the data --> Update random numbers --> look at the data --> Update ranodm numbers
```

🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.rand.html


In [60]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6944, 0.8021, 0.7488, 0.5755],
        [0.5218, 0.7988, 0.5007, 0.8390],
        [0.0252, 0.8823, 0.4083, 0.1070]])

In [61]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [62]:
# Create New Random Tensor
Random_1 = torch.rand(size = (5,4,3))
Random_1 , Random_1.ndim, Random_1.shape

(tensor([[[0.9319, 0.6750, 0.2557],
          [0.9386, 0.4273, 0.2903],
          [0.1687, 0.9873, 0.1509],
          [0.4033, 0.5205, 0.1269]],
 
         [[0.1978, 0.2829, 0.1690],
          [0.1282, 0.0049, 0.2204],
          [0.9577, 0.1989, 0.8935],
          [0.9295, 0.1803, 0.0354]],
 
         [[0.5416, 0.9350, 0.3268],
          [0.4599, 0.9703, 0.1552],
          [0.2003, 0.0861, 0.9640],
          [0.0153, 0.2752, 0.4741]],
 
         [[0.9778, 0.7421, 0.6788],
          [0.7834, 0.6633, 0.9936],
          [0.4636, 0.0630, 0.5290],
          [0.2374, 0.4496, 0.3083]],
 
         [[0.8929, 0.8455, 0.2789],
          [0.2426, 0.3764, 0.2232],
          [0.7251, 0.7569, 0.1351],
          [0.5630, 0.9244, 0.3359]]]), 3, torch.Size([5, 4, 3]))

### 📕 Zeros and Ones


🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.zeros.html

🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.ones.html

In [63]:
# Create a tensor of all zeros
Zeros = torch.zeros(size = (3,4))
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
# Create a tensors of all ones
ones = torch.ones(size = (4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### 📕Creating range of tensors and tenosr-like


🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.arange.html


🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.zeros_like.html

In [65]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 211, step = 2)
one_to_ten

tensor([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,
         29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
         57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,  83,
         85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111,
        113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139,
        141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
        169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195,
        197, 199, 201, 203, 205, 207, 209])

In [66]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0])

### 📕Tensor Datatypes

**🔑Note:** Tensor datatypes is one of the 3 big errors you will run into with Pytorch:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [67]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,  # what datatype is the tensor
                               device = None, # The device of the constructed tensor. If None and data is a tensor then the device of data is used. If None and data is not a tensor then the result tensor is constructed on the CPU.
                               requires_grad = False # if need to fine gradient
                               )
float_32_tensor

tensor([3., 6., 9.])

In [68]:
float_32_tensor.dtype

torch.float32

In [69]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [70]:
int_32_tensors = torch.tensor([3, 6, 9 ],
                              dtype = torch.int32)
int_32_tensors

tensor([3, 6, 9], dtype=torch.int32)

In [71]:
float_32_tensor * int_32_tensors

tensor([ 9., 36., 81.])

### 📕 Tensor Attributes

Getting Information from tensor

1. Get datatype from a tensor can use`tensor.dtype`
2. to get shape from a tensor can use `tensor.shape`
3. to get device from a tensor, can use `tensor.device`

In [72]:
# create tensor
some_tensor = torch.rand(size = (3, 4))
some_tensor

tensor([[0.4101, 0.1220, 0.8469, 0.7597],
        [0.9935, 0.1581, 0.4004, 0.2599],
        [0.5950, 0.2841, 0.2674, 0.5219]])

In [73]:
# Print out details about some_tensor
print(some_tensor)
print(f"Datatype of some_tensor is:{some_tensor.dtype}")
print(f"Shape of some_tensor is:{some_tensor.shape}")
print(f"device of some_tensor is:{some_tensor.device}")

tensor([[0.4101, 0.1220, 0.8469, 0.7597],
        [0.9935, 0.1581, 0.4004, 0.2599],
        [0.5950, 0.2841, 0.2674, 0.5219]])
Datatype of some_tensor is:torch.float32
Shape of some_tensor is:torch.Size([3, 4])
device of some_tensor is:cpu


### 📕 Manipulating Tensor

Tensor Operations include:
1. Addition
2. subtraction
3. Multiplication ( element-wise)
4. Division 
5. Matrix multiplication


There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
 * ` (3, 2) @ (3, 2) ` won't work
 *  `(2, 3) @ (3, 2) ` will work
 *  `(3, 2) @ (2, 3)` will work

2. Resulting matrix has the shape of the **outer dimension**
 *  `(2, 3) @ (3, 2) ` -> `(2, 2)`
 *  `(3, 2) @ (2, 3)` -> `(3, 3)`

In [74]:
# Create tensor
tensor_A = torch.tensor([1, 2, 45])
tensor_A + 12

tensor([13, 14, 57])

In [75]:
# Multiply tensor by 10
tensor_A * 10

tensor([ 10,  20, 450])

In [76]:
# Devision tensor by 10
tensor_A / 10

tensor([0.1000, 0.2000, 4.5000])

In [77]:
# Subtraction tensor by 10
tensor_A - 10

tensor([-9, -8, 35])

In [78]:
# Try out Pytorch in-built function
torch.mul(tensor_A, 10)

tensor([ 10,  20, 450])

In [79]:
torch.add(tensor_A , tensor_A)

tensor([ 2,  4, 90])

In [80]:
# Create tensor_B
tensor_B = torch.tensor([[3, 2, 45],
                         [4, 5, 6],
                         [5, 6, 10]])

# Matirx Mutliplication
torch.matmul(tensor_A, tensor_B)

tensor([236, 282, 507])

In [85]:
# Shape Errors : when both has same dimension and try to do matrix multipication
tensor_C = torch.tensor([[1,2],
                         [3,4],
                         [5,7]])

tensor_D = torch.tensor([[3,5],
                         [10,3],
                         [5,6]])

torch.mm(tensor_C, tensor_D.T) # did transpose of tensor_D

tensor([[13, 16, 17],
        [29, 42, 39],
        [50, 71, 67]])

### 📕 Tensor Aggregation
1. Min
2. Max
3. Mean
4. Sum


In [88]:
# Create a tensor
X = torch.arange(0, 10, 3)
X 

tensor([0, 3, 6, 9])

In [89]:
# Find the Min
torch.min(X)

tensor(0)

In [90]:
# Find the max
torch.max(X)

tensor(9)

In [93]:
#Find the mean
torch.mean(X.type(dtype = torch.float32))

tensor(4.5000)

In [97]:
# Find the summ
torch.sum(X)

tensor(18)