<a href="https://colab.research.google.com/github/RD191295/Pytorch-Tutorials/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##📗 Pytorch Fundamentals

### 📕***Introduction to Pytorch***
<p align="justify"> PyTorch is an open-source library used in machine learning library developed using Torch library for python program. It is developed by Facebook’s AI Research lab and released in January 2016 as a free and open-source library mainly used in computer vision, deep learning, and natural language processing applications. Programmer can build a complex neural network with ease using PyTorch as it has a core data structure, Tensor, multi-dimensional array like Numpy arrays. PyTorch use is increasing in current industries and in the research community as it is flexible, faster, easy to get the project up and running, due to which PyTorch is one of the top deep learning tools.<p>



🔖**Source Link:** https://pytorch.org/

In [88]:
import torch
print(torch.__version__)

1.13.1+cu116


In [89]:
!nvidia-smi

Mon Apr  3 16:29:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P0    26W /  70W |    573MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 📗Introduction to Tensors

###📕Creating Tensors

🔖**Source Link**: https://pytorch.org/docs/stable/tensors.html

In [90]:
# Scalar 
scalar  = torch.tensor(7)
scalar

tensor(7)

In [91]:
# Scalar has no dimension !!
scalar.ndim

0

In [92]:
# Vectors
Vector = torch.tensor([7,1])
Vector

tensor([7, 1])

In [93]:
# Vector has 1 dimension!!
Vector.ndim

1

In [94]:
# Vector shape
Vector.shape

torch.Size([2])

In [95]:
# Matric
Matrix = torch.tensor([[7, 8],
                       [9, 10]])

Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [96]:
# Matric has 2 dim
Matrix.ndim

2

In [97]:
# Matrix shape
Matrix.shape

torch.Size([2, 2])

In [98]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [99]:
# Tensor dimension --- it has N dimension
TENSOR.ndim

3

In [100]:
# Tensor shape
TENSOR.shape

torch.Size([1, 3, 3])

In [101]:
# Tensor Example 2
Tensor_2 = torch.tensor([[[1,2,3],
                          [3,2,5]],
                         [[4,3,5],
                          [5,6,7]]])
Tensor_2

tensor([[[1, 2, 3],
         [3, 2, 5]],

        [[4, 3, 5],
         [5, 6, 7]]])

In [102]:
# Tensor_2 Shape
Tensor_2.shape

torch.Size([2, 2, 3])

### 📕 Random Tensors

Why Random Tensors❓

Random tensors are important because the way many nerual networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``` 
Start with random numbers --> look at the data --> Update random numbers --> look at the data --> Update ranodm numbers
```

🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.rand.html


In [103]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7749, 0.8208, 0.2793, 0.6817],
        [0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294]])

In [104]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [105]:
# Create New Random Tensor
Random_1 = torch.rand(size = (5,4,3))
Random_1 , Random_1.ndim, Random_1.shape

(tensor([[[0.3940, 0.3469, 0.1459],
          [0.0454, 0.8159, 0.5036],
          [0.6007, 0.6584, 0.4109],
          [0.2333, 0.8381, 0.1091]],
 
         [[0.9584, 0.0128, 0.4813],
          [0.5963, 0.3217, 0.3314],
          [0.2028, 0.1269, 0.0742],
          [0.1051, 0.9332, 0.9103]],
 
         [[0.0926, 0.9609, 0.7868],
          [0.6911, 0.5609, 0.7034],
          [0.4121, 0.0550, 0.2476],
          [0.1249, 0.6033, 0.8041]],
 
         [[0.8806, 0.0570, 0.5975],
          [0.4692, 0.9430, 0.0755],
          [0.9589, 0.8139, 0.2305],
          [0.5514, 0.2681, 0.8950]],
 
         [[0.0874, 0.1130, 0.0637],
          [0.8740, 0.4538, 0.7753],
          [0.2465, 0.6181, 0.0559],
          [0.9661, 0.3524, 0.1406]]]),
 3,
 torch.Size([5, 4, 3]))

### 📕 Zeros and Ones


🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.zeros.html

🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.ones.html

In [106]:
# Create a tensor of all zeros
Zeros = torch.zeros(size = (3,4))
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [107]:
# Create a tensors of all ones
ones = torch.ones(size = (4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### 📕Creating range of tensors and tenosr-like


🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.arange.html


🔖**Source Link:** https://pytorch.org/docs/stable/generated/torch.zeros_like.html

In [108]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 211, step = 2)
one_to_ten

tensor([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,
         29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
         57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,  83,
         85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111,
        113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139,
        141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
        169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195,
        197, 199, 201, 203, 205, 207, 209])

In [109]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0])

### 📕Tensor Datatypes

**🔑Note:** Tensor datatypes is one of the 3 big errors you will run into with Pytorch:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [110]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,  # what datatype is the tensor
                               device = None, # The device of the constructed tensor. If None and data is a tensor then the device of data is used. If None and data is not a tensor then the result tensor is constructed on the CPU.
                               requires_grad = False # if need to fine gradient
                               )
float_32_tensor

tensor([3., 6., 9.])

In [111]:
float_32_tensor.dtype

torch.float32

In [112]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [113]:
int_32_tensors = torch.tensor([3, 6, 9 ],
                              dtype = torch.int32)
int_32_tensors

tensor([3, 6, 9], dtype=torch.int32)

In [114]:
float_32_tensor * int_32_tensors

tensor([ 9., 36., 81.])

### 📕 Tensor Attributes

Getting Information from tensor

1. Get datatype from a tensor can use`tensor.dtype`
2. to get shape from a tensor can use `tensor.shape`
3. to get device from a tensor, can use `tensor.device`

In [115]:
# create tensor
some_tensor = torch.rand(size = (3, 4))
some_tensor

tensor([[0.9390, 0.8314, 0.2307, 0.1861],
        [0.2356, 0.7590, 0.6418, 0.5569],
        [0.3205, 0.7441, 0.1187, 0.0123]])

In [116]:
# Print out details about some_tensor
print(some_tensor)
print(f"Datatype of some_tensor is:{some_tensor.dtype}")
print(f"Shape of some_tensor is:{some_tensor.shape}")
print(f"device of some_tensor is:{some_tensor.device}")

tensor([[0.9390, 0.8314, 0.2307, 0.1861],
        [0.2356, 0.7590, 0.6418, 0.5569],
        [0.3205, 0.7441, 0.1187, 0.0123]])
Datatype of some_tensor is:torch.float32
Shape of some_tensor is:torch.Size([3, 4])
device of some_tensor is:cpu


### 📕 Manipulating Tensor

Tensor Operations include:
1. Addition
2. subtraction
3. Multiplication ( element-wise)
4. Division 
5. Matrix multiplication


There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
 * ` (3, 2) @ (3, 2) ` won't work
 *  `(2, 3) @ (3, 2) ` will work
 *  `(3, 2) @ (2, 3)` will work

2. Resulting matrix has the shape of the **outer dimension**
 *  `(2, 3) @ (3, 2) ` -> `(2, 2)`
 *  `(3, 2) @ (2, 3)` -> `(3, 3)`

In [117]:
# Create tensor
tensor_A = torch.tensor([1, 2, 45])
tensor_A + 12

tensor([13, 14, 57])

In [118]:
# Multiply tensor by 10
tensor_A * 10

tensor([ 10,  20, 450])

In [119]:
# Devision tensor by 10
tensor_A / 10

tensor([0.1000, 0.2000, 4.5000])

In [120]:
# Subtraction tensor by 10
tensor_A - 10

tensor([-9, -8, 35])

In [121]:
# Try out Pytorch in-built function
torch.mul(tensor_A, 10)

tensor([ 10,  20, 450])

In [122]:
torch.add(tensor_A , tensor_A)

tensor([ 2,  4, 90])

In [123]:
# Create tensor_B
tensor_B = torch.tensor([[3, 2, 45],
                         [4, 5, 6],
                         [5, 6, 10]])

# Matirx Mutliplication
torch.matmul(tensor_A, tensor_B)

tensor([236, 282, 507])

In [124]:
# Shape Errors : when both has same dimension and try to do matrix multipication
tensor_C = torch.tensor([[1,2],
                         [3,4],
                         [5,7]])

tensor_D = torch.tensor([[3,5],
                         [10,3],
                         [5,6]])

torch.mm(tensor_C, tensor_D.T) # did transpose of tensor_D

tensor([[13, 16, 17],
        [29, 42, 39],
        [50, 71, 67]])

### 📕 Tensor Aggregation
1. Min
2. Max
3. Mean
4. Sum


In [125]:
# Create a tensor
X = torch.arange(0, 10, 3)
X 

tensor([0, 3, 6, 9])

In [126]:
# Find the Min
torch.min(X)

tensor(0)

In [127]:
# Find the max
torch.max(X)

tensor(9)

In [128]:
#Find the mean
torch.mean(X.type(dtype = torch.float32))

tensor(4.5000)

In [129]:
# Find the summ
torch.sum(X)

tensor(18)

### 📕 Positional min/max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).


In [130]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### 📕 change tensor datatype
As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

First we'll create a tensor and check it's datatype (the default is torch.float32).

In [131]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [132]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [133]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)



> **Note:** Different datatypes can be confusing to begin with. But think of it like this, the lower the number (e.g. 32, 16, 8), the less precise a computer stores the value. And with a lower amount of storage, this generally results in faster computation and a smaller overall model. Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts. For more on this, I'd read up about precision in computing).



>**Exercise:** So far we've covered a fair few tensor methods but there's a bunch more in the torch.Tensor documentation, I'd recommend spending 10-minutes scrolling through and looking into any that catch your eye. Click on them and then write them out in code yourself to see what happens.


### 📕Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make the right elements of your tensors are mixing with the right elements of other tensors. 

Let's try them out.

First, we'll create a tensor.

In [134]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [135]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [136]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [137]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [138]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [139]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])


In [140]:
# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [141]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])


In [142]:
## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [143]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

In [144]:
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## 📕 Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [145]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [146]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [147]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [148]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [149]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [150]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

### 📕 PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are: 
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor. 
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

Let's try them out.

In [151]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [152]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [153]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [154]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### 📕 Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short: 

``start with random numbers -> tensor operations -> try to make better (again and again and again)``

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right? 

In [155]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,3)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Running tensors and Pytorch objexts on the GPUS (making faster computations !!!)

# Getting a GPU

In [156]:
!nvidia-smi

Mon Apr  3 16:29:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P0    26W /  70W |    573MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Check for GPU access with PyTorch

In [157]:
torch.cuda.is_available()

True

In [158]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [159]:
# count no of device
torch.cuda.device_count()

1

## Putting tensors(and models ) on the GPU

In [160]:
# create a tensor ( default on the GPU)
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [161]:
# Move tensor to GPU ( if available)
tensor_gpu = tensor.to(device)
print(tensor_gpu)

tensor([1, 2, 3], device='cuda:0')


In [162]:
# Moving tensor back to GPU

tensor = tensor_gpu.cpu()
tensor.numpy()

array([1, 2, 3])

# Excercise and Extra Curriculm

## **1. Documentation reading**

> A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):




*   The documentation on [torch.Tensor](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
*  The documentation on [torch.cuda](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).

## **2. Create a random tensor with shape (7, 7).**


In [163]:
random_tensor = torch.rand(size = (7,7))  
random_tensor

tensor([[0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274, 0.2696, 0.4414, 0.2969],
        [0.8317, 0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050],
        [0.3068, 0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913]])

## **3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).**

In [164]:
random_tensor_2 = torch.rand(size = (7,1))

# Matirx Mutliplication
torch.matmul(random_tensor, random_tensor_2)

tensor([[1.6023],
        [1.6286],
        [1.2705],
        [2.2861],
        [2.2581],
        [1.8172],
        [1.8756]])

# **Set the random seed to 0 and do 2 & 3 over again.**

In [165]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(size = (7,7))  
random_tensor_2 = torch.rand(size = (7,1))

# Matirx Mutliplication
torch.matmul(random_tensor, random_tensor_2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

## **5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)**

In [170]:
torch.cuda.manual_seed(1234)

## 6. **Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:**

In [166]:
torch.manual_seed(1234)
random_tensor_A = torch.rand(size = (2,3))  
random_tensor_B = torch.rand(size = (2,3))  

In [168]:
device = "cuda" if torch.cuda.is_available() else "cpu"
# Move tensor to GPU ( if available)
random_tensor_A_GPU = random_tensor_A.to(device)
random_tensor_B_GPU = random_tensor_B.to(device)

random_tensor_A_GPU,random_tensor_B_GPU

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

## **7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).**

In [174]:
# Matirx Mutliplication
tensor_mat_AB = torch.matmul(random_tensor_A_GPU,random_tensor_B_GPU.T)

# **8. Find the maximum and minimum values of the output of 7.**

In [175]:
max_value = torch.max(tensor_mat_AB)
min_value = torch.min(tensor_mat_AB)

max_value, min_value

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

## **9. Find the maximum and minimum index values of the output of 7.**


In [176]:
max_index = torch.argmax(tensor_mat_AB)
min_index = torch.argmin(tensor_mat_AB)

max_index,min_index

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

## **10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.**

In [179]:
torch.manual_seed(7)

first_tensor = torch.rand(size = (1,1,1,10))
second_tensor = torch.squeeze(first_tensor)

first_tensor,second_tensor

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))